### ISSUE TITLE
Error de registro

### ISSUE THREAD

**Issue by Nidev-lab** [gsantolaya/school-project-frontend#58]
## Proceso

1. Ingrese a la pagina
2. Intente registrarme con un usuario nuevo.

## Resultado esperado

• Al completar el formulario de registro con mis datos poder registrarme.

## Resultado actual

•No me puedo registrar y genera error en la consola.

## Captura

![image](https://github.com/gsantolaya/school-project-frontend/assets/53904695/dbd730d0-0bdb-4e94-94cd-78394dd53ddb)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by gsantolaya** [comment]
Se habia cumplido el tiempo de prueba de Railway, problema solucionado.

**Comment by Nidev-lab** [comment]
Perfecto! Con eso estamos.
